/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WasThisHelpful {
        "doneText": string;
        "feedbackQuestion": string;
        "feedbackStyle": string;
        "happyFeedback": string;
        "iconStyle": string;
        "question": string;
        "sadFeedback": string;
        "session": string;
    }
}
declare global {
    interface HTMLWasThisHelpfulElement extends Components.WasThisHelpful, HTMLStencilElement {
    }
    var HTMLWasThisHelpfulElement: {
        prototype: HTMLWasThisHelpfulElement;
        new (): HTMLWasThisHelpfulElement;
    };
    interface HTMLElementTagNameMap {
        "was-this-helpful": HTMLWasThisHelpfulElement;
    }
}
declare namespace LocalJSX {
    interface WasThisHelpful {
        "doneText"?: string;
        "feedbackQuestion"?: string;
        "feedbackStyle"?: string;
        "happyFeedback"?: string;
        "iconStyle"?: string;
        "onAdditionalFeedback"?: (event: CustomEvent<any>) => void;
        "onEverything"?: (event: CustomEvent<any>) => void;
        "onFeedback"?: (event: CustomEvent<any>) => void;
        "onResponse"?: (event: CustomEvent<any>) => void;
        "question"?: string;
        "sadFeedback"?: string;
        "session"?: string;
    }
    interface IntrinsicElements {
        "was-this-helpful": WasThisHelpful;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "was-this-helpful": LocalJSX.WasThisHelpful & JSXBase.HTMLAttributes<HTMLWasThisHelpfulElement>;
        }
    }
}
