/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WasThisHelpful {
        "feedbackPlaceholder": string;
        "feedbackTitle": string;
        "title": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWasThisHelpfulElement extends Components.WasThisHelpful, HTMLStencilElement {
    }
    var HTMLWasThisHelpfulElement: {
        prototype: HTMLWasThisHelpfulElement;
        new (): HTMLWasThisHelpfulElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "was-this-helpful": HTMLWasThisHelpfulElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WasThisHelpful {
        "feedbackPlaceholder"?: string;
        "feedbackTitle"?: string;
        "onOptionSelected"?: (event: CustomEvent<any>) => void;
        "title"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "was-this-helpful": WasThisHelpful;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "was-this-helpful": LocalJSX.WasThisHelpful & JSXBase.HTMLAttributes<HTMLWasThisHelpfulElement>;
        }
    }
}
